# Generated by Django 4.2.13 on 2024-07-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0018_alter_basicdetails_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_form.basicdetails'),
        ),
    ]
