# Generated by Django 4.2.13 on 2024-07-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form', '0019_alter_preference_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='states',
            field=models.CharField(max_length=25),
        ),
    ]
